apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgres-image-catalog
    major: 17
  bootstrap:
    initdb:
      database: shaikh
      owner: app
      secret: do this
  storage:
    size: 20Gi
    storageClass: fast-local-ssd
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
      tolerations:
        - key: "node-role.kubernetes.io/postgres"
          operator: "Exists"
          effect: "NoSchedule"
