apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shaikh-db
  namespace: db
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgres-image-catalog
    major: 17
  bootstrap:
    initdb:
      database: shaikh
      owner: shaikh
      secret:
        name: shaikh-owner-secret
      postInitSQL:
        - CREATE SCHEMA IF NOT EXISTS paradedb;
        - CREATE SCHEMA IF NOT EXISTS rag;
        - CREATE EXTENSION IF NOT EXISTS pg_search WITH SCHEMA paradedb;
        - CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
        - CREATE EXTENSION IF NOT EXISTS vectorscale WITH SCHEMA public;
  storage:
    size: 30Gi
    storageClass: fast-local-ssd
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
      tolerations:
        - key: "node-role.kubernetes.io/postgres"
          operator: "Exists"
          effect: "NoSchedule"
