apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shaikh-db
  namespace: db
spec:
  instances: 1
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectStore: gcs-store
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgres-image-catalog
    major: 17
  bootstrap:
    initdb:
      database: shaikh
      owner: shaikh
      secret:
        name: shaikh-owner-secret
      postInitSQL:
        - CREATE SCHEMA IF NOT EXISTS paradedb;
        - CREATE SCHEMA IF NOT EXISTS rag;
        - CREATE EXTENSION IF NOT EXISTS pg_search WITH SCHEMA paradedb;
        - CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
        - CREATE EXTENSION IF NOT EXISTS vectorscale WITH SCHEMA public;
      postgresql:
        parameters:
          shared_buffers: "512MB"
          work_mem: "4MB"
          maintenance_work_mem: "64MB"
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "2Gi"
          cpu: "1"
  storage:
    size: 20Gi
    storageClass: fast-local-ssd
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
      tolerations:
        - key: "node-role.kubernetes.io/postgres"
          operator: "Exists"
          effect: "NoSchedule"
