apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./k8s/postgres
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cnpg
    - name: barman
    - name: cert-manager
    - name: rancher
