apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./k8s/namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
