apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-storage
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./k8s/local-path-storage
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespaces
