apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./clusters/kind/cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespaces
