apiVersion: v1
kind: ConfigMap
metadata:
  name: shaikh-db-config
  namespace: db
data:
  values.yaml: |
    cluster:
      name: shaikh-db
      instances: 1

    bootstrap:
      database: shaikh
      owner: shaikh

    imageCatalog:
      image: ghcr.io/awbalessa/shaikh/postgres:17.6-v0.1.1

    postgresqlParameters:
      shared_buffers: "512MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"

    resources:
      requests: { cpu: "1", memory: "2Gi" }
      limits: { cpu: "1", memory: "2Gi" }

    storage:
      size: 20Gi
      class: standard

    backup:
      destinationPath: "gs://shaikh-dev-bucket/backups/physical"
      retentionPolicy: "30d"

    external:
      enabled: true
      name: source

    pooler:
      enabled: true
      instances: 3
      parameters:
        max_client_conn: "500"
        default_pool_size: "20"
        reserve_pool_size: "5"
        reserve_pool_timeout: "5"
        idle_transaction_timeout: "60"
      resources:
        requests: { cpu: "100m", memory: "128Mi" }
        limits: { cpu: "500m", memory: "256Mi" }

    seed:
      enabled: true
      gcsDumpPath: gs://shaikh-dev-bucket/backups/logical/latest.dump

    scheduledBackup:
      enabled: true
      schedule: "0 0 2 * * 0"
      immediate: false
      suspend: false
