apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shaikh-db
  namespace: db
spec:
  interval: 10m
  releaseName: shaikh-db
  chart:
    spec:
      chart: ./charts/postgres
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: shaikh-db-values
      valuesKey: values.yaml
    - kind: Secret
      name: shaikh-db-secrets
      valuesKey: values.yaml
