apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shaikh-db
  namespace: db
spec:
  interval: 10m
  releaseName: shaikh-db
  chart:
    spec:
      chart: postgres
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: ghcr
        namespace: flux-system
