apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shaikh-db
  namespace: db
spec:
  instances: 1
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectStore: gcs-store
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgres-image-catalog
    major: 17
  bootstrap:
    initdb:
      database: shaikh
      owner: shaikh
      secret:
        name: shaikh-owner-secret
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectStore: gcs-store
  postgresql:
    parameters:
      shared_buffers: "512MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"
  storage:
    size: 20Gi
    storageClass: cnpg-local
  monitoring:
    enablePodMonitor: true
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: "node-role.kubernetes.io/postgres"
        operator: "Exists"
        effect: "NoSchedule"
  managed:
    roles:
      - name: shaikh-sudo
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: shaikh-sudo-secret
