apiVersion: batch/v1
kind: Job
metadata:
  name: pg-seed-import
  namespace: db
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: dump-volume
          emptyDir: {}
        - name: gcs-sa-key
          secret:
            secretName: gcs-sa-key
      initContainers:
        - name: fetch-dump
          image: google/cloud-sdk:slim
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              echo "🔑 Activating service account..."
              gcloud auth activate-service-account --key-file=/var/secrets/gcs-sa-key.json
              echo "📥 Downloading dump from GCS..."
              gsutil cp gs://shaikh-dev-bucket/backups/logical/latest.dump /dumps/latest.dump
          volumeMounts:
            - name: gcs-sa-key
              mountPath: /var/secrets
              readOnly: true
            - name: dump-volume
              mountPath: /dumps
      containers:
        - name: restore-dump
          image: postgres:17.6
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              echo "📦 Restoring data into Postgres..."
              PGPASSWORD=$POSTGRES_PASSWORD \
              pg_restore \
                -U shaikh-sudo \
                -h shaikh-db-rw.db.svc.cluster.local \
                -d shaikh \
                -j 4 \
                --clean --no-owner --no-privileges \
                /dumps/latest.dump
              echo "✅ Import complete"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shaikh-sudo-secret
                  key: password
          volumeMounts:
            - name: dump-volume
              mountPath: /dumps
