// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ayat.sql

package database

import (
	"context"
)

const getAyatByKeys = `-- name: GetAyatByKeys :many
SELECT surah, ayah, ar, ar_uthmani, en FROM ayat
WHERE surah = $1
    AND ayah = ANY($2::int[])
`

type GetAyatByKeysParams struct {
	Surah int32
	Ayat  []int32
}

func (q *Queries) GetAyatByKeys(ctx context.Context, arg GetAyatByKeysParams) ([]Ayat, error) {
	rows, err := q.db.Query(ctx, getAyatByKeys, arg.Surah, arg.Ayat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ayat
	for rows.Next() {
		var i Ayat
		if err := rows.Scan(
			&i.Surah,
			&i.Ayah,
			&i.Ar,
			&i.ArUthmani,
			&i.En,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
