apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 10m
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      version: "1.27.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    installCRDs: true
