kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: shaikh
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "role=control-plane,env=dev"

  - role: worker
    extraMounts:
      - hostPath: ./volume/postgres
        containerPath: /mnt/postgres
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "stateful=true,node-role.kubernetes.io/postgres="

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "stateful=true"

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "stateful=false"
