apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'cnpg'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  action: keep
                  regex: cnpg
                - source_labels: [__meta_kubernetes_pod_container_port_number]
                  action: keep
                  regex: "9187"
        target_allocator:
          endpoint: http://otel-cnpg-gateway-targetallocator
          interval: 30s
          collector_id: "${POD_NAME}"
      filelog:
        include:
          - "/var/log/pods/*/*/*.log"
        start_at: beginning
        operators:
          - type: container
    processors:
      batch: {}
    exporters:
      prometheusremotewrite:
        endpoint: "http://mimir.observability.svc.cluster.local:8080/api/v1/push"
      otlphttp:
        endpoint: "http://loki.observability.svc.cluster.local/otlp"
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [filelog]
          processors: [batch]
          exporters: [otlphttp]
