apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shaikh-db
  namespace: db
spec:
  interval: 10m
  releaseName: shaikh-db
  chart:
    spec:
      chart: ./k8s/postgres
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFiles:
    - values.yaml
    - values.secrets.yaml
