// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chunks.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const lexicalSearch = `-- name: LexicalSearch :many
WITH ranked_chunks AS (
    SELECT
    id,
    paradedb.score(id)::float8 AS score,
    embedded_chunk,
    raw_chunk,
    source,
    surah,
    ayah
    FROM chunks
    WHERE id @@@ paradedb.boolean(
    must => ARRAY[
        paradedb.boolean(
        should => ARRAY[
            paradedb.match('tokenized_chunk', $2::text),
            paradedb.match('tokenized_chunk_title', $2::text)
        ]
        )
    ]
    ||
    CASE
        WHEN $3::content_type IS NOT NULL
        THEN ARRAY[paradedb.term('content_type', $3::content_type)]
        ELSE ARRAY[]::paradedb.searchqueryinput[]
    END
    ||
    CASE
        WHEN $4::source IS NOT NULL
        THEN ARRAY[paradedb.term('source', $4::source)]
        ELSE ARRAY[]::paradedb.searchqueryinput[]
    END
    ||
    CASE
        WHEN $5::int IS NOT NULL
        THEN ARRAY[paradedb.term('surah', $5::int)]
        ELSE ARRAY[]::paradedb.searchqueryinput[]
    END
    ||
    CASE
        WHEN $5::int IS NOT NULL
        AND $6::int IS NOT NULL
        AND $7::int IS NOT NULL
        THEN ARRAY[paradedb.range('ayah', int4range($6, $7, '[]'))]
        ELSE ARRAY[]::paradedb.searchqueryinput[]
    END
    )
), deduped_chunks AS (
  SELECT DISTINCT ON (raw_chunk)
    id,
    score,
    embedded_chunk,
    source,
    surah,
    ayah
  FROM ranked_chunks
  ORDER BY raw_chunk, score DESC
)
SELECT id, score, embedded_chunk, source, surah, ayah FROM deduped_chunks
ORDER BY score DESC
LIMIT $1
`

type LexicalSearchParams struct {
	NumberOfChunks int32
	Query          string
	ContentType    NullContentType
	Source         NullSource
	Surah          pgtype.Int4
	AyahStart      pgtype.Int4
	AyahEnd        pgtype.Int4
}

type LexicalSearchRow struct {
	ID            int64
	Score         float64
	EmbeddedChunk string
	Source        Source
	Surah         pgtype.Int4
	Ayah          pgtype.Int4
}

func (q *Queries) LexicalSearch(ctx context.Context, arg LexicalSearchParams) ([]LexicalSearchRow, error) {
	rows, err := q.db.Query(ctx, lexicalSearch,
		arg.NumberOfChunks,
		arg.Query,
		arg.ContentType,
		arg.Source,
		arg.Surah,
		arg.AyahStart,
		arg.AyahEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LexicalSearchRow
	for rows.Next() {
		var i LexicalSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.EmbeddedChunk,
			&i.Source,
			&i.Surah,
			&i.Ayah,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const semanticSearch = `-- name: SemanticSearch :many
WITH ranked_chunks AS (
    SELECT
        id,
        (1 - (embedding <=> $2::vector))::float8 as score,
        embedded_chunk,
        raw_chunk,
        source,
        surah,
        ayah
    FROM chunks
    WHERE (
    cardinality($3::smallint[]) = 0
    OR labels && $3::smallint[]
    )
), deduped_chunks AS (
    SELECT DISTINCT ON (raw_chunk)
        id,
        score,
        embedded_chunk,
        source,
        surah,
        ayah
    FROM ranked_chunks
    ORDER BY raw_chunk, score DESC
    )
SELECT id, score, embedded_chunk, source, surah, ayah FROM deduped_chunks
ORDER BY score DESC
LIMIT $1
`

type SemanticSearchParams struct {
	NumberOfChunks int32
	Vector         pgvector_go.Vector
	LabelFilters   []int16
}

type SemanticSearchRow struct {
	ID            int64
	Score         float64
	EmbeddedChunk string
	Source        Source
	Surah         pgtype.Int4
	Ayah          pgtype.Int4
}

func (q *Queries) SemanticSearch(ctx context.Context, arg SemanticSearchParams) ([]SemanticSearchRow, error) {
	rows, err := q.db.Query(ctx, semanticSearch, arg.NumberOfChunks, arg.Vector, arg.LabelFilters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SemanticSearchRow
	for rows.Next() {
		var i SemanticSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.EmbeddedChunk,
			&i.Source,
			&i.Surah,
			&i.Ayah,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
