apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k-root
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./clusters/kind/kustomizations
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
