package models

const (
	SurahNumberFatiha                SurahNumber = 1
	SurahNumberBaqarah               SurahNumber = 2
	SurahNumberAlImran               SurahNumber = 3
	SurahNumberNisa                  SurahNumber = 4
	SurahNumberMaidah                SurahNumber = 5
	SurahNumberAnam                  SurahNumber = 6
	SurahNumberAraf                  SurahNumber = 7
	SurahNumberAnfal                 SurahNumber = 8
	SurahNumberTawbah                SurahNumber = 9
	SurahNumberYunus                 SurahNumber = 10
	SurahNumberHud                   SurahNumber = 11
	SurahNumberYusuf                 SurahNumber = 12
	SurahNumberRad                   SurahNumber = 13
	SurahNumberIbrahim               SurahNumber = 14
	SurahNumberHijr                  SurahNumber = 15
	SurahNumberNahl                  SurahNumber = 16
	SurahNumberIsra                  SurahNumber = 17
	SurahNumberKahf                  SurahNumber = 18
	SurahNumberMaryam                SurahNumber = 19
	SurahNumberTaha                  SurahNumber = 20
	SurahNumberAnbiya                SurahNumber = 21
	SurahNumberHajj                  SurahNumber = 22
	SurahNumberMuminun               SurahNumber = 23
	SurahNumberNur                   SurahNumber = 24
	SurahNumberFurqan                SurahNumber = 25
	SurahNumberShuara                SurahNumber = 26
	SurahNumberNaml                  SurahNumber = 27
	SurahNumberQasas                 SurahNumber = 28
	SurahNumberAnkabut               SurahNumber = 29
	SurahNumberRum                   SurahNumber = 30
	SurahNumberLuqman                SurahNumber = 31
	SurahNumberSajdah                SurahNumber = 32
	SurahNumberAhzab                 SurahNumber = 33
	SurahNumberSaba                  SurahNumber = 34
	SurahNumberFatir                 SurahNumber = 35
	SurahNumberYasin                 SurahNumber = 36
	SurahNumberSaffat                SurahNumber = 37
	SurahNumberSad                   SurahNumber = 38
	SurahNumberZumar                 SurahNumber = 39
	SurahNumberGhafir                SurahNumber = 40
	SurahNumberFussilat              SurahNumber = 41
	SurahNumberShura                 SurahNumber = 42
	SurahNumberZukhruf               SurahNumber = 43
	SurahNumberDukhan                SurahNumber = 44
	SurahNumberJathiyah              SurahNumber = 45
	SurahNumberAhqaf                 SurahNumber = 46
	SurahNumberMuhammad              SurahNumber = 47
	SurahNumberFath                  SurahNumber = 48
	SurahNumberHujurat               SurahNumber = 49
	SurahNumberQaf                   SurahNumber = 50
	SurahNumberDhariyat              SurahNumber = 51
	SurahNumberTur                   SurahNumber = 52
	SurahNumberNajm                  SurahNumber = 53
	SurahNumberQamar                 SurahNumber = 54
	SurahNumberRahman                SurahNumber = 55
	SurahNumberWaqiah                SurahNumber = 56
	SurahNumberHadid                 SurahNumber = 57
	SurahNumberMujadilah             SurahNumber = 58
	SurahNumberHashr                 SurahNumber = 59
	SurahNumberMumtahanah            SurahNumber = 60
	SurahNumberSaff                  SurahNumber = 61
	SurahNumberJumuah                SurahNumber = 62
	SurahNumberMunafiqun             SurahNumber = 63
	SurahNumberTaghabun              SurahNumber = 64
	SurahNumberTalaq                 SurahNumber = 65
	SurahNumberTahrim                SurahNumber = 66
	SurahNumberMulk                  SurahNumber = 67
	SurahNumberQalam                 SurahNumber = 68
	SurahNumberHaqqah                SurahNumber = 69
	SurahNumberMaarij                SurahNumber = 70
	SurahNumberNuh                   SurahNumber = 71
	SurahNumberJinn                  SurahNumber = 72
	SurahNumberMuzzammil             SurahNumber = 73
	SurahNumberMuddathir             SurahNumber = 74
	SurahNumberQiyamah               SurahNumber = 75
	SurahNumberInsan                 SurahNumber = 76
	SurahNumberMursalat              SurahNumber = 77
	SurahNumberNaba                  SurahNumber = 78
	SurahNumberNaziat                SurahNumber = 79
	SurahNumberAbasa                 SurahNumber = 80
	SurahNumberTakwir                SurahNumber = 81
	SurahNumberInfitar               SurahNumber = 82
	SurahNumberMutaffifin            SurahNumber = 83
	SurahNumberInshiqaq              SurahNumber = 84
	SurahNumberBuruj                 SurahNumber = 85
	SurahNumberTariq                 SurahNumber = 86
	SurahNumberAla                   SurahNumber = 87
	SurahNumberGhashiyah             SurahNumber = 88
	SurahNumberFajr                  SurahNumber = 89
	SurahNumberBalad                 SurahNumber = 90
	SurahNumberShams                 SurahNumber = 91
	SurahNumberLail                  SurahNumber = 92
	SurahNumberDuha                  SurahNumber = 93
	SurahNumberSharh                 SurahNumber = 94
	SurahNumberTin                   SurahNumber = 95
	SurahNumberAlaq                  SurahNumber = 96
	SurahNumberQadr                  SurahNumber = 97
	SurahNumberBayyinah              SurahNumber = 98
	SurahNumberZalzalah              SurahNumber = 99
	SurahNumberAdiyat                SurahNumber = 100
	SurahNumberQariah                SurahNumber = 101
	SurahNumberTakathur              SurahNumber = 102
	SurahNumberAsr                   SurahNumber = 103
	SurahNumberHumazah               SurahNumber = 104
	SurahNumberFil                   SurahNumber = 105
	SurahNumberQuraish               SurahNumber = 106
	SurahNumberMaun                  SurahNumber = 107
	SurahNumberKauthar               SurahNumber = 108
	SurahNumberKafirun               SurahNumber = 109
	SurahNumberNasr                  SurahNumber = 110
	SurahNumberLahab                 SurahNumber = 111
	SurahNumberIkhlas                SurahNumber = 112
	SurahNumberFalaq                 SurahNumber = 113
	SurahNumberNas                   SurahNumber = 114
	SuraNameFatiha                   SurahName   = "Surat Al-Fatiha"
	SuraNameBaqarah                  SurahName   = "Surat Al-Baqarah"
	SuraNameAlImran                  SurahName   = "Surat Al-Imran"
	SuraNameNisa                     SurahName   = "Surat Al-Nesaa"
	SuraNameMaidah                   SurahName   = "Surat Al-Ma'idah"
	SuraNameAnam                     SurahName   = "Surat Al-An'aam"
	SuraNameAraf                     SurahName   = "Surat Al-A'raf"
	SuraNameAnfal                    SurahName   = "Surat Al-Anfal"
	SuraNameTawbah                   SurahName   = "Surat At-Tawbah"
	SuraNameYunus                    SurahName   = "Surat Yunus"
	SuraNameHud                      SurahName   = "Surat Hud"
	SuraNameYusuf                    SurahName   = "Surat Yusuf"
	SuraNameRad                      SurahName   = "Surat Ar-Ra'd"
	SuraNameIbrahim                  SurahName   = "Surat Ibrahim"
	SuraNameHijr                     SurahName   = "Surat Al-Hijr"
	SuraNameNahl                     SurahName   = "Surat An-Nahl"
	SuraNameIsra                     SurahName   = "Surat Al-Isra'"
	SuraNameKahf                     SurahName   = "Surat Al-Kahf"
	SuraNameMaryam                   SurahName   = "Surat Maryam"
	SuraNameTaha                     SurahName   = "Surat Taha"
	SuraNameAnbiya                   SurahName   = "Surat Al-Anbiya"
	SuraNameHajj                     SurahName   = "Surat Al-Hajj"
	SuraNameMuminun                  SurahName   = "Surat Al-Mu'minun"
	SuraNameNur                      SurahName   = "Surat An-Nur"
	SuraNameFurqan                   SurahName   = "Surat Al-Furqan"
	SuraNameShuara                   SurahName   = "Surat Ash-Shu'ara"
	SuraNameNaml                     SurahName   = "Surat An-Naml"
	SuraNameQasas                    SurahName   = "Surat Al-Qasas"
	SuraNameAnkabut                  SurahName   = "Surat Al-Ankabut"
	SuraNameRum                      SurahName   = "Surat Ar-Rum"
	SuraNameLuqman                   SurahName   = "Surat Luqman"
	SuraNameSajdah                   SurahName   = "Surat As-Sajdah"
	SuraNameAhzab                    SurahName   = "Surat Al-Ahzab"
	SuraNameSaba                     SurahName   = "Surat Saba"
	SuraNameFatir                    SurahName   = "Surat Fatir"
	SuraNameYasin                    SurahName   = "Surat Ya-Sin"
	SuraNameSaffat                   SurahName   = "Surat As-Saffat"
	SuraNameSad                      SurahName   = "Surat Sad"
	SuraNameZumar                    SurahName   = "Surat Az-Zumar"
	SuraNameGhafir                   SurahName   = "Surat Ghafir"
	SuraNameFussilat                 SurahName   = "Surat Fussilat"
	SuraNameShura                    SurahName   = "Surat Ash-Shura"
	SuraNameZukhruf                  SurahName   = "Surat Az-Zukhruf"
	SuraNameDukhan                   SurahName   = "Surat Ad-Dukhan"
	SuraNameJathiyah                 SurahName   = "Surat Al-Jathiyah"
	SuraNameAhqaf                    SurahName   = "Surat Al-Ahqaf"
	SuraNameMuhammad                 SurahName   = "Surat Muhammad"
	SuraNameFath                     SurahName   = "Surat Al-Fath"
	SuraNameHujurat                  SurahName   = "Surat Al-Hujurat"
	SuraNameQaf                      SurahName   = "Surat Qaf"
	SuraNameDhariyat                 SurahName   = "Surat Ath-Thariyat"
	SuraNameTur                      SurahName   = "Surat At-Tur"
	SuraNameNajm                     SurahName   = "Surat An-Najm"
	SuraNameQamar                    SurahName   = "Surat Al-Qamar"
	SuraNameRahman                   SurahName   = "Surat Ar-Rahman"
	SuraNameWaqiah                   SurahName   = "Surat Al-Waqi'ah"
	SuraNameHadid                    SurahName   = "Surat Al-Hadid"
	SuraNameMujadilah                SurahName   = "Surat Al-Mujadila"
	SuraNameHashr                    SurahName   = "Surat Al-Hashr"
	SuraNameMumtahanah               SurahName   = "Surat Al-Mumtahinah"
	SuraNameSaff                     SurahName   = "Surat As-Saff"
	SuraNameJumuah                   SurahName   = "Surat Al-Jumu'ah"
	SuraNameMunafiqun                SurahName   = "Surat Al-Munafiqun"
	SuraNameTaghabun                 SurahName   = "Surat At-Taghabun"
	SuraNameTalaq                    SurahName   = "Surat At-Talaq"
	SuraNameTahrim                   SurahName   = "Surat At-Tahrim"
	SuraNameMulk                     SurahName   = "Surat Al-Mulk"
	SuraNameQalam                    SurahName   = "Surat Al-Qalam"
	SuraNameHaqqah                   SurahName   = "Surat Al-Haqqah"
	SuraNameMaarij                   SurahName   = "Surat Al-Ma'arij"
	SuraNameNuh                      SurahName   = "Surat Nuh"
	SuraNameJinn                     SurahName   = "Surat Al-Jinn"
	SuraNameMuzzammil                SurahName   = "Surat Al-Muzzammil"
	SuraNameMuddathir                SurahName   = "Surat Al-Muddathir"
	SuraNameQiyamah                  SurahName   = "Surat Al-Qiyāmah"
	SuraNameInsan                    SurahName   = "Surat Al-Insan"
	SuraNameMursalat                 SurahName   = "Surat Al-Mursalat"
	SuraNameNaba                     SurahName   = "Surat An-Naba"
	SuraNameNaziat                   SurahName   = "Surat An-Nazi'at"
	SuraNameAbasa                    SurahName   = "Surat 'Abasa"
	SuraNameTakwir                   SurahName   = "Surat At-Takwir"
	SuraNameInfitar                  SurahName   = "Surat Al-Infitar"
	SuraNameMutaffifin               SurahName   = "Surat Al-Mutaffifin"
	SuraNameInshiqaq                 SurahName   = "Surat Al-Inshiqaq"
	SuraNameBuruj                    SurahName   = "Surat Al-Buruj"
	SuraNameTariq                    SurahName   = "Surat At-Tariq"
	SuraNameAlaa                     SurahName   = "Surat Al-A'laa"
	SuraNameGhashiyah                SurahName   = "Surat Al-Ghashiyah"
	SuraNameFajr                     SurahName   = "Surat Al-Fajr"
	SuraNameBalad                    SurahName   = "Surat Al-Balad"
	SuraNameShams                    SurahName   = "Surat Ash-Shams"
	SuraNameLail                     SurahName   = "Surat Al-Lail"
	SuraNameDuha                     SurahName   = "Surat Ad-Duha"
	SuraNameSharh                    SurahName   = "Surat Ash-Sharh"
	SuraNameTin                      SurahName   = "Surat At-Tin"
	SuraNameAlaq                     SurahName   = "Surat Al-'Alaq"
	SuraNameQadr                     SurahName   = "Surat Al-Qadr"
	SuraNameBayyinah                 SurahName   = "Surat Al-Bayyinah"
	SuraNameZalzalah                 SurahName   = "Surat Az-Zalzalah"
	SuraNameAdiyat                   SurahName   = "Surat Al-'Adiyat"
	SuraNameQariah                   SurahName   = "Surat Al-Qari'ah"
	SuraNameTakathur                 SurahName   = "Surat At-Takathur"
	SuraNameAsr                      SurahName   = "Surat Al-'Asr"
	SuraNameHumazah                  SurahName   = "Surat Al-Humazah"
	SuraNameFil                      SurahName   = "Surat Al-Fil"
	SuraNameQuraish                  SurahName   = "Surat Quraish"
	SuraNameMaun                     SurahName   = "Surat Al-Ma'un"
	SuraNameKawthar                  SurahName   = "Surat Al-Kawthar"
	SuraNameKafirun                  SurahName   = "Surat Al-Kafirun"
	SuraNameNasr                     SurahName   = "Surat An-Nasr"
	SuraNameLahab                    SurahName   = "Surat Al-Masad"
	SuraNameIkhlas                   SurahName   = "Surat Al-Ikhlas"
	SuraNameFalaq                    SurahName   = "Surat Al-Falaq"
	SuraNameNas                      SurahName   = "Surat An-Nas"
	AyahNumberOne                    AyahNumber  = 1
	AyahNumberTwo                    AyahNumber  = 2
	AyahNumberThree                  AyahNumber  = 3
	AyahNumberFour                   AyahNumber  = 4
	AyahNumberFive                   AyahNumber  = 5
	AyahNumberSix                    AyahNumber  = 6
	AyahNumberSeven                  AyahNumber  = 7
	AyahNumberEight                  AyahNumber  = 8
	AyahNumberNine                   AyahNumber  = 9
	AyahNumberTen                    AyahNumber  = 10
	AyahNumberEleven                 AyahNumber  = 11
	AyahNumberTwelve                 AyahNumber  = 12
	AyahNumberThirteen               AyahNumber  = 13
	AyahNumberFourteen               AyahNumber  = 14
	AyahNumberFifteen                AyahNumber  = 15
	AyahNumberSixteen                AyahNumber  = 16
	AyahNumberSeventeen              AyahNumber  = 17
	AyahNumberEighteen               AyahNumber  = 18
	AyahNumberNineteen               AyahNumber  = 19
	AyahNumberTwenty                 AyahNumber  = 20
	AyahNumberTwentyOne              AyahNumber  = 21
	AyahNumberTwentyTwo              AyahNumber  = 22
	AyahNumberTwentyThree            AyahNumber  = 23
	AyahNumberTwentyFour             AyahNumber  = 24
	AyahNumberTwentyFive             AyahNumber  = 25
	AyahNumberTwentySix              AyahNumber  = 26
	AyahNumberTwentySeven            AyahNumber  = 27
	AyahNumberTwentyEight            AyahNumber  = 28
	AyahNumberTwentyNine             AyahNumber  = 29
	AyahNumberThirty                 AyahNumber  = 30
	AyahNumberThirtyOne              AyahNumber  = 31
	AyahNumberThirtyTwo              AyahNumber  = 32
	AyahNumberThirtyThree            AyahNumber  = 33
	AyahNumberThirtyFour             AyahNumber  = 34
	AyahNumberThirtyFive             AyahNumber  = 35
	AyahNumberThirtySix              AyahNumber  = 36
	AyahNumberThirtySeven            AyahNumber  = 37
	AyahNumberThirtyEight            AyahNumber  = 38
	AyahNumberThirtyNine             AyahNumber  = 39
	AyahNumberFourty                 AyahNumber  = 40
	AyahNumberFourtyOne              AyahNumber  = 41
	AyahNumberFourtyTwo              AyahNumber  = 42
	AyahNumberFourtyThree            AyahNumber  = 43
	AyahNumberFourtyFour             AyahNumber  = 44
	AyahNumberFourtyFive             AyahNumber  = 45
	AyahNumberFourtySix              AyahNumber  = 46
	AyahNumberFourtySeven            AyahNumber  = 47
	AyahNumberFourtyEight            AyahNumber  = 48
	AyahNumberFourtyNine             AyahNumber  = 49
	AyahNumberFifty                  AyahNumber  = 50
	AyahNumberFiftyOne               AyahNumber  = 51
	AyahNumberFiftyTwo               AyahNumber  = 52
	AyahNumberFiftyThree             AyahNumber  = 53
	AyahNumberFiftyFour              AyahNumber  = 54
	AyahNumberFiftyFive              AyahNumber  = 55
	AyahNumberFiftySix               AyahNumber  = 56
	AyahNumberFiftySeven             AyahNumber  = 57
	AyahNumberFiftyEight             AyahNumber  = 58
	AyahNumberFiftyNine              AyahNumber  = 59
	AyahNumberSixty                  AyahNumber  = 60
	AyahNumberSixtyOne               AyahNumber  = 61
	AyahNumberSixtyTwo               AyahNumber  = 62
	AyahNumberSixtyThree             AyahNumber  = 63
	AyahNumberSixtyFour              AyahNumber  = 64
	AyahNumberSixtyFive              AyahNumber  = 65
	AyahNumberSixtySix               AyahNumber  = 66
	AyahNumberSixtySeven             AyahNumber  = 67
	AyahNumberSixtyEight             AyahNumber  = 68
	AyahNumberSixtyNine              AyahNumber  = 69
	AyahNumberSeventy                AyahNumber  = 70
	AyahNumberSeventyOne             AyahNumber  = 71
	AyahNumberSeventyTwo             AyahNumber  = 72
	AyahNumberSeventyThree           AyahNumber  = 73
	AyahNumberSeventyFour            AyahNumber  = 74
	AyahNumberSeventyFive            AyahNumber  = 75
	AyahNumberSeventySix             AyahNumber  = 76
	AyahNumberSeventySeven           AyahNumber  = 77
	AyahNumberSeventyEight           AyahNumber  = 78
	AyahNumberSeventyNine            AyahNumber  = 79
	AyahNumberEighty                 AyahNumber  = 80
	AyahNumberEightyOne              AyahNumber  = 81
	AyahNumberEightyTwo              AyahNumber  = 82
	AyahNumberEightyThree            AyahNumber  = 83
	AyahNumberEightyFour             AyahNumber  = 84
	AyahNumberEightyFive             AyahNumber  = 85
	AyahNumberEightySix              AyahNumber  = 86
	AyahNumberEightySeven            AyahNumber  = 87
	AyahNumberEightyEight            AyahNumber  = 88
	AyahNumberEightyNine             AyahNumber  = 89
	AyahNumberNinety                 AyahNumber  = 90
	AyahNumberNinetyOne              AyahNumber  = 91
	AyahNumberNinetyTwo              AyahNumber  = 92
	AyahNumberNinetyThree            AyahNumber  = 93
	AyahNumberNinetyFour             AyahNumber  = 94
	AyahNumberNinetyFive             AyahNumber  = 95
	AyahNumberNinetySix              AyahNumber  = 96
	AyahNumberNinetySeven            AyahNumber  = 97
	AyahNumberNinetyEight            AyahNumber  = 98
	AyahNumberNinetyNine             AyahNumber  = 99
	AyahNumberHundred                AyahNumber  = 100
	AyahNumberHundredOne             AyahNumber  = 101
	AyahNumberHundredTwo             AyahNumber  = 102
	AyahNumberHundredThree           AyahNumber  = 103
	AyahNumberHundredFour            AyahNumber  = 104
	AyahNumberHundredFive            AyahNumber  = 105
	AyahNumberHundredSix             AyahNumber  = 106
	AyahNumberHundredSeven           AyahNumber  = 107
	AyahNumberHundredEight           AyahNumber  = 108
	AyahNumberHundredNine            AyahNumber  = 109
	AyahNumberHundredTen             AyahNumber  = 110
	AyahNumberHundredEleven          AyahNumber  = 111
	AyahNumberHundredTwelve          AyahNumber  = 112
	AyahNumberHundredThirteen        AyahNumber  = 113
	AyahNumberHundredFourteen        AyahNumber  = 114
	AyahNumberHundredFifteen         AyahNumber  = 115
	AyahNumberHundredSixteen         AyahNumber  = 116
	AyahNumberHundredSeventeen       AyahNumber  = 117
	AyahNumberHundredEighteen        AyahNumber  = 118
	AyahNumberHundredNineteen        AyahNumber  = 119
	AyahNumberHundredTwenty          AyahNumber  = 120
	AyahNumberHundredTwentyOne       AyahNumber  = 121
	AyahNumberHundredTwentyTwo       AyahNumber  = 122
	AyahNumberHundredTwentyThree     AyahNumber  = 123
	AyahNumberHundredTwentyFour      AyahNumber  = 124
	AyahNumberHundredTwentyFive      AyahNumber  = 125
	AyahNumberHundredTwentySix       AyahNumber  = 126
	AyahNumberHundredTwentySeven     AyahNumber  = 127
	AyahNumberHundredTwentyEight     AyahNumber  = 128
	AyahNumberHundredTwentyNine      AyahNumber  = 129
	AyahNumberHundredThirty          AyahNumber  = 130
	AyahNumberHundredThirtyOne       AyahNumber  = 131
	AyahNumberHundredThirtyTwo       AyahNumber  = 132
	AyahNumberHundredThirtyThree     AyahNumber  = 133
	AyahNumberHundredThirtyFour      AyahNumber  = 134
	AyahNumberHundredThirtyFive      AyahNumber  = 135
	AyahNumberHundredThirtySix       AyahNumber  = 136
	AyahNumberHundredThirtySeven     AyahNumber  = 137
	AyahNumberHundredThirtyEight     AyahNumber  = 138
	AyahNumberHundredThirtyNine      AyahNumber  = 139
	AyahNumberHundredFourty          AyahNumber  = 140
	AyahNumberHundredFourtyOne       AyahNumber  = 141
	AyahNumberHundredFourtyTwo       AyahNumber  = 142
	AyahNumberHundredFourtyThree     AyahNumber  = 143
	AyahNumberHundredFourtyFour      AyahNumber  = 144
	AyahNumberHundredFourtyFive      AyahNumber  = 145
	AyahNumberHundredFourtySix       AyahNumber  = 146
	AyahNumberHundredFourtySeven     AyahNumber  = 147
	AyahNumberHundredFourtyEight     AyahNumber  = 148
	AyahNumberHundredFourtyNine      AyahNumber  = 149
	AyahNumberHundredFifty           AyahNumber  = 150
	AyahNumberHundredFiftyOne        AyahNumber  = 151
	AyahNumberHundredFiftyTwo        AyahNumber  = 152
	AyahNumberHundredFiftyThree      AyahNumber  = 153
	AyahNumberHundredFiftyFour       AyahNumber  = 154
	AyahNumberHundredFiftyFive       AyahNumber  = 155
	AyahNumberHundredFiftySix        AyahNumber  = 156
	AyahNumberHundredFiftySeven      AyahNumber  = 157
	AyahNumberHundredFiftyEight      AyahNumber  = 158
	AyahNumberHundredFiftyNine       AyahNumber  = 159
	AyahNumberHundredSixty           AyahNumber  = 160
	AyahNumberHundredSixtyOne        AyahNumber  = 161
	AyahNumberHundredSixtyTwo        AyahNumber  = 162
	AyahNumberHundredSixtyThree      AyahNumber  = 163
	AyahNumberHundredSixtyFour       AyahNumber  = 164
	AyahNumberHundredSixtyFive       AyahNumber  = 165
	AyahNumberHundredSixtySix        AyahNumber  = 166
	AyahNumberHundredSixtySeven      AyahNumber  = 167
	AyahNumberHundredSixtyEight      AyahNumber  = 168
	AyahNumberHundredSixtyNine       AyahNumber  = 169
	AyahNumberHundredSeventy         AyahNumber  = 170
	AyahNumberHundredSeventyOne      AyahNumber  = 171
	AyahNumberHundredSeventyTwo      AyahNumber  = 172
	AyahNumberHundredSeventyThree    AyahNumber  = 173
	AyahNumberHundredSeventyFour     AyahNumber  = 174
	AyahNumberHundredSeventyFive     AyahNumber  = 175
	AyahNumberHundredSeventySix      AyahNumber  = 176
	AyahNumberHundredSeventySeven    AyahNumber  = 177
	AyahNumberHundredSeventyEight    AyahNumber  = 178
	AyahNumberHundredSeventyNine     AyahNumber  = 179
	AyahNumberHundredEighty          AyahNumber  = 180
	AyahNumberHundredEightyOne       AyahNumber  = 181
	AyahNumberHundredEightyTwo       AyahNumber  = 182
	AyahNumberHundredEightyThree     AyahNumber  = 183
	AyahNumberHundredEightyFour      AyahNumber  = 184
	AyahNumberHundredEightyFive      AyahNumber  = 185
	AyahNumberHundredEightySix       AyahNumber  = 186
	AyahNumberHundredEightySeven     AyahNumber  = 187
	AyahNumberHundredEightyEight     AyahNumber  = 188
	AyahNumberHundredEightyNine      AyahNumber  = 189
	AyahNumberHundredNinety          AyahNumber  = 190
	AyahNumberHundredNinetyOne       AyahNumber  = 191
	AyahNumberHundredNinetyTwo       AyahNumber  = 192
	AyahNumberHundredNinetyThree     AyahNumber  = 193
	AyahNumberHundredNinetyFour      AyahNumber  = 194
	AyahNumberHundredNinetyFive      AyahNumber  = 195
	AyahNumberHundredNinetySix       AyahNumber  = 196
	AyahNumberHundredNinetySeven     AyahNumber  = 197
	AyahNumberHundredNinetyEight     AyahNumber  = 198
	AyahNumberHundredNinetyNine      AyahNumber  = 199
	AyahNumberTwoHundred             AyahNumber  = 200
	AyahNumberTwoHundredOne          AyahNumber  = 201
	AyahNumberTwoHundredTwo          AyahNumber  = 202
	AyahNumberTwoHundredThree        AyahNumber  = 203
	AyahNumberTwoHundredFour         AyahNumber  = 204
	AyahNumberTwoHundredFive         AyahNumber  = 205
	AyahNumberTwoHundredSix          AyahNumber  = 206
	AyahNumberTwoHundredSeven        AyahNumber  = 207
	AyahNumberTwoHundredEight        AyahNumber  = 208
	AyahNumberTwoHundredNine         AyahNumber  = 209
	AyahNumberTwoHundredTen          AyahNumber  = 210
	AyahNumberTwoHundredEleven       AyahNumber  = 211
	AyahNumberTwoHundredTwelve       AyahNumber  = 212
	AyahNumberTwoHundredThirteen     AyahNumber  = 213
	AyahNumberTwoHundredFourteen     AyahNumber  = 214
	AyahNumberTwoHundredFifteen      AyahNumber  = 215
	AyahNumberTwoHundredSixteen      AyahNumber  = 216
	AyahNumberTwoHundredSeventeen    AyahNumber  = 217
	AyahNumberTwoHundredEighteen     AyahNumber  = 218
	AyahNumberTwoHundredNineteen     AyahNumber  = 219
	AyahNumberTwoHundredTwenty       AyahNumber  = 220
	AyahNumberTwoHundredTwentyOne    AyahNumber  = 221
	AyahNumberTwoHundredTwentyTwo    AyahNumber  = 222
	AyahNumberTwoHundredTwentyThree  AyahNumber  = 223
	AyahNumberTwoHundredTwentyFour   AyahNumber  = 224
	AyahNumberTwoHundredTwentyFive   AyahNumber  = 225
	AyahNumberTwoHundredTwentySix    AyahNumber  = 226
	AyahNumberTwoHundredTwentySeven  AyahNumber  = 227
	AyahNumberTwoHundredTwentyEight  AyahNumber  = 228
	AyahNumberTwoHundredTwentyNine   AyahNumber  = 229
	AyahNumberTwoHundredThirty       AyahNumber  = 230
	AyahNumberTwoHundredThirtyOne    AyahNumber  = 231
	AyahNumberTwoHundredThirtyTwo    AyahNumber  = 232
	AyahNumberTwoHundredThirtyThree  AyahNumber  = 233
	AyahNumberTwoHundredThirtyFour   AyahNumber  = 234
	AyahNumberTwoHundredThirtyFive   AyahNumber  = 235
	AyahNumberTwoHundredThirtySix    AyahNumber  = 236
	AyahNumberTwoHundredThirtySeven  AyahNumber  = 237
	AyahNumberTwoHundredThirtyEight  AyahNumber  = 238
	AyahNumberTwoHundredThirtyNine   AyahNumber  = 239
	AyahNumberTwoHundredFourty       AyahNumber  = 240
	AyahNumberTwoHundredFourtyOne    AyahNumber  = 241
	AyahNumberTwoHundredFourtyTwo    AyahNumber  = 242
	AyahNumberTwoHundredFourtyThree  AyahNumber  = 243
	AyahNumberTwoHundredFourtyFour   AyahNumber  = 244
	AyahNumberTwoHundredFourtyFive   AyahNumber  = 245
	AyahNumberTwoHundredFourtySix    AyahNumber  = 246
	AyahNumberTwoHundredFourtySeven  AyahNumber  = 247
	AyahNumberTwoHundredFourtyEight  AyahNumber  = 248
	AyahNumberTwoHundredFourtyNine   AyahNumber  = 249
	AyahNumberTwoHundredFifty        AyahNumber  = 250
	AyahNumberTwoHundredFiftyOne     AyahNumber  = 251
	AyahNumberTwoHundredFiftyTwo     AyahNumber  = 252
	AyahNumberTwoHundredFiftyThree   AyahNumber  = 253
	AyahNumberTwoHundredFiftyFour    AyahNumber  = 254
	AyahNumberTwoHundredFiftyFive    AyahNumber  = 255
	AyahNumberTwoHundredFiftySix     AyahNumber  = 256
	AyahNumberTwoHundredFiftySeven   AyahNumber  = 257
	AyahNumberTwoHundredFiftyEight   AyahNumber  = 258
	AyahNumberTwoHundredFiftyNine    AyahNumber  = 259
	AyahNumberTwoHundredSixty        AyahNumber  = 260
	AyahNumberTwoHundredSixtyOne     AyahNumber  = 261
	AyahNumberTwoHundredSixtyTwo     AyahNumber  = 262
	AyahNumberTwoHundredSixtyThree   AyahNumber  = 263
	AyahNumberTwoHundredSixtyFour    AyahNumber  = 264
	AyahNumberTwoHundredSixtyFive    AyahNumber  = 265
	AyahNumberTwoHundredSixtySix     AyahNumber  = 266
	AyahNumberTwoHundredSixtySeven   AyahNumber  = 267
	AyahNumberTwoHundredSixtyEight   AyahNumber  = 268
	AyahNumberTwoHundredSixtyNine    AyahNumber  = 269
	AyahNumberTwoHundredSeventy      AyahNumber  = 270
	AyahNumberTwoHundredSeventyOne   AyahNumber  = 271
	AyahNumberTwoHundredSeventyTwo   AyahNumber  = 272
	AyahNumberTwoHundredSeventyThree AyahNumber  = 273
	AyahNumberTwoHundredSeventyFour  AyahNumber  = 274
	AyahNumberTwoHundredSeventyFive  AyahNumber  = 275
	AyahNumberTwoHundredSeventySix   AyahNumber  = 276
	AyahNumberTwoHundredSeventySeven AyahNumber  = 277
	AyahNumberTwoHundredSeventyEight AyahNumber  = 278
	AyahNumberTwoHundredSeventyNine  AyahNumber  = 279
	AyahNumberTwoHundredEighty       AyahNumber  = 280
	AyahNumberTwoHundredEightyOne    AyahNumber  = 281
	AyahNumberTwoHundredEightyTwo    AyahNumber  = 282
	AyahNumberTwoHundredEightyThree  AyahNumber  = 283
	AyahNumberTwoHundredEightyFour   AyahNumber  = 284
	AyahNumberTwoHundredEightyFive   AyahNumber  = 285
	AyahNumberTwoHundredEightySix    AyahNumber  = 286
)

type SurahNumber int
type SurahName string
type AyahNumber int
