package models

const (
	SurahNumberFatiha     SurahNumber = 1
	SurahNumberBaqarah    SurahNumber = 2
	SurahNumberAlImran    SurahNumber = 3
	SurahNumberNisa       SurahNumber = 4
	SurahNumberMaidah     SurahNumber = 5
	SurahNumberAnam       SurahNumber = 6
	SurahNumberAraf       SurahNumber = 7
	SurahNumberAnfal      SurahNumber = 8
	SurahNumberTawbah     SurahNumber = 9
	SurahNumberYunus      SurahNumber = 10
	SurahNumberHud        SurahNumber = 11
	SurahNumberYusuf      SurahNumber = 12
	SurahNumberRad        SurahNumber = 13
	SurahNumberIbrahim    SurahNumber = 14
	SurahNumberHijr       SurahNumber = 15
	SurahNumberNahl       SurahNumber = 16
	SurahNumberIsra       SurahNumber = 17
	SurahNumberKahf       SurahNumber = 18
	SurahNumberMaryam     SurahNumber = 19
	SurahNumberTaha       SurahNumber = 20
	SurahNumberAnbiya     SurahNumber = 21
	SurahNumberHajj       SurahNumber = 22
	SurahNumberMuminun    SurahNumber = 23
	SurahNumberNur        SurahNumber = 24
	SurahNumberFurqan     SurahNumber = 25
	SurahNumberShuara     SurahNumber = 26
	SurahNumberNaml       SurahNumber = 27
	SurahNumberQasas      SurahNumber = 28
	SurahNumberAnkabut    SurahNumber = 29
	SurahNumberRum        SurahNumber = 30
	SurahNumberLuqman     SurahNumber = 31
	SurahNumberSajdah     SurahNumber = 32
	SurahNumberAhzab      SurahNumber = 33
	SurahNumberSaba       SurahNumber = 34
	SurahNumberFatir      SurahNumber = 35
	SurahNumberYasin      SurahNumber = 36
	SurahNumberSaffat     SurahNumber = 37
	SurahNumberSad        SurahNumber = 38
	SurahNumberZumar      SurahNumber = 39
	SurahNumberGhafir     SurahNumber = 40
	SurahNumberFussilat   SurahNumber = 41
	SurahNumberShura      SurahNumber = 42
	SurahNumberZukhruf    SurahNumber = 43
	SurahNumberDukhan     SurahNumber = 44
	SurahNumberJathiyah   SurahNumber = 45
	SurahNumberAhqaf      SurahNumber = 46
	SurahNumberMuhammad   SurahNumber = 47
	SurahNumberFath       SurahNumber = 48
	SurahNumberHujurat    SurahNumber = 49
	SurahNumberQaf        SurahNumber = 50
	SurahNumberDhariyat   SurahNumber = 51
	SurahNumberTur        SurahNumber = 52
	SurahNumberNajm       SurahNumber = 53
	SurahNumberQamar      SurahNumber = 54
	SurahNumberRahman     SurahNumber = 55
	SurahNumberWaqiah     SurahNumber = 56
	SurahNumberHadid      SurahNumber = 57
	SurahNumberMujadilah  SurahNumber = 58
	SurahNumberHashr      SurahNumber = 59
	SurahNumberMumtahanah SurahNumber = 60
	SurahNumberSaff       SurahNumber = 61
	SurahNumberJumuah     SurahNumber = 62
	SurahNumberMunafiqun  SurahNumber = 63
	SurahNumberTaghabun   SurahNumber = 64
	SurahNumberTalaq      SurahNumber = 65
	SurahNumberTahrim     SurahNumber = 66
	SurahNumberMulk       SurahNumber = 67
	SurahNumberQalam      SurahNumber = 68
	SurahNumberHaqqah     SurahNumber = 69
	SurahNumberMaarij     SurahNumber = 70
	SurahNumberNuh        SurahNumber = 71
	SurahNumberJinn       SurahNumber = 72
	SurahNumberMuzzammil  SurahNumber = 73
	SurahNumberMuddathir  SurahNumber = 74
	SurahNumberQiyamah    SurahNumber = 75
	SurahNumberInsan      SurahNumber = 76
	SurahNumberMursalat   SurahNumber = 77
	SurahNumberNaba       SurahNumber = 78
	SurahNumberNaziat     SurahNumber = 79
	SurahNumberAbasa      SurahNumber = 80
	SurahNumberTakwir     SurahNumber = 81
	SurahNumberInfitar    SurahNumber = 82
	SurahNumberMutaffifin SurahNumber = 83
	SurahNumberInshiqaq   SurahNumber = 84
	SurahNumberBuruj      SurahNumber = 85
	SurahNumberTariq      SurahNumber = 86
	SurahNumberAla        SurahNumber = 87
	SurahNumberGhashiyah  SurahNumber = 88
	SurahNumberFajr       SurahNumber = 89
	SurahNumberBalad      SurahNumber = 90
	SurahNumberShams      SurahNumber = 91
	SurahNumberLail       SurahNumber = 92
	SurahNumberDuha       SurahNumber = 93
	SurahNumberSharh      SurahNumber = 94
	SurahNumberTin        SurahNumber = 95
	SurahNumberAlaq       SurahNumber = 96
	SurahNumberQadr       SurahNumber = 97
	SurahNumberBayyinah   SurahNumber = 98
	SurahNumberZalzalah   SurahNumber = 99
	SurahNumberAdiyat     SurahNumber = 100
	SurahNumberQariah     SurahNumber = 101
	SurahNumberTakathur   SurahNumber = 102
	SurahNumberAsr        SurahNumber = 103
	SurahNumberHumazah    SurahNumber = 104
	SurahNumberFil        SurahNumber = 105
	SurahNumberQuraish    SurahNumber = 106
	SurahNumberMaun       SurahNumber = 107
	SurahNumberKauthar    SurahNumber = 108
	SurahNumberKafirun    SurahNumber = 109
	SurahNumberNasr       SurahNumber = 110
	SurahNumberLahab      SurahNumber = 111
	SurahNumberIkhlas     SurahNumber = 112
	SurahNumberFalaq      SurahNumber = 113
	SurahNumberNas        SurahNumber = 114
	SuraNameFatiha        SurahName   = "Surat Al-Fatiha"
	SuraNameBaqarah       SurahName   = "Surat Al-Baqarah"
	SuraNameAlImran       SurahName   = "Surat Al-Imran"
	SuraNameNisa          SurahName   = "Surat Al-Nesaa"
	SuraNameMaidah        SurahName   = "Surat Al-Ma'idah"
	SuraNameAnam          SurahName   = "Surat Al-An'aam"
	SuraNameAraf          SurahName   = "Surat Al-A'raf"
	SuraNameAnfal         SurahName   = "Surat Al-Anfal"
	SuraNameTawbah        SurahName   = "Surat At-Tawbah"
	SuraNameYunus         SurahName   = "Surat Yunus"
	SuraNameHud           SurahName   = "Surat Hud"
	SuraNameYusuf         SurahName   = "Surat Yusuf"
	SuraNameRad           SurahName   = "Surat Ar-Ra'd"
	SuraNameIbrahim       SurahName   = "Surat Ibrahim"
	SuraNameHijr          SurahName   = "Surat Al-Hijr"
	SuraNameNahl          SurahName   = "Surat An-Nahl"
	SuraNameIsra          SurahName   = "Surat Al-Isra'"
	SuraNameKahf          SurahName   = "Surat Al-Kahf"
	SuraNameMaryam        SurahName   = "Surat Maryam"
	SuraNameTaha          SurahName   = "Surat Taha"
	SuraNameAnbiya        SurahName   = "Surat Al-Anbiya"
	SuraNameHajj          SurahName   = "Surat Al-Hajj"
	SuraNameMuminun       SurahName   = "Surat Al-Mu'minun"
	SuraNameNur           SurahName   = "Surat An-Nur"
	SuraNameFurqan        SurahName   = "Surat Al-Furqan"
	SuraNameShuara        SurahName   = "Surat Ash-Shu'ara"
	SuraNameNaml          SurahName   = "Surat An-Naml"
	SuraNameQasas         SurahName   = "Surat Al-Qasas"
	SuraNameAnkabut       SurahName   = "Surat Al-Ankabut"
	SuraNameRum           SurahName   = "Surat Ar-Rum"
	SuraNameLuqman        SurahName   = "Surat Luqman"
	SuraNameSajdah        SurahName   = "Surat As-Sajdah"
	SuraNameAhzab         SurahName   = "Surat Al-Ahzab"
	SuraNameSaba          SurahName   = "Surat Saba"
	SuraNameFatir         SurahName   = "Surat Fatir"
	SuraNameYasin         SurahName   = "Surat Ya-Sin"
	SuraNameSaffat        SurahName   = "Surat As-Saffat"
	SuraNameSad           SurahName   = "Surat Sad"
	SuraNameZumar         SurahName   = "Surat Az-Zumar"
	SuraNameGhafir        SurahName   = "Surat Ghafir"
	SuraNameFussilat      SurahName   = "Surat Fussilat"
	SuraNameShura         SurahName   = "Surat Ash-Shura"
	SuraNameZukhruf       SurahName   = "Surat Az-Zukhruf"
	SuraNameDukhan        SurahName   = "Surat Ad-Dukhan"
	SuraNameJathiyah      SurahName   = "Surat Al-Jathiyah"
	SuraNameAhqaf         SurahName   = "Surat Al-Ahqaf"
	SuraNameMuhammad      SurahName   = "Surat Muhammad"
	SuraNameFath          SurahName   = "Surat Al-Fath"
	SuraNameHujurat       SurahName   = "Surat Al-Hujurat"
	SuraNameQaf           SurahName   = "Surat Qaf"
	SuraNameDhariyat      SurahName   = "Surat Ath-Thariyat"
	SuraNameTur           SurahName   = "Surat At-Tur"
	SuraNameNajm          SurahName   = "Surat An-Najm"
	SuraNameQamar         SurahName   = "Surat Al-Qamar"
	SuraNameRahman        SurahName   = "Surat Ar-Rahman"
	SuraNameWaqiah        SurahName   = "Surat Al-Waqi'ah"
	SuraNameHadid         SurahName   = "Surat Al-Hadid"
	SuraNameMujadilah     SurahName   = "Surat Al-Mujadila"
	SuraNameHashr         SurahName   = "Surat Al-Hashr"
	SuraNameMumtahanah    SurahName   = "Surat Al-Mumtahinah"
	SuraNameSaff          SurahName   = "Surat As-Saff"
	SuraNameJumuah        SurahName   = "Surat Al-Jumu'ah"
	SuraNameMunafiqun     SurahName   = "Surat Al-Munafiqun"
	SuraNameTaghabun      SurahName   = "Surat At-Taghabun"
	SuraNameTalaq         SurahName   = "Surat At-Talaq"
	SuraNameTahrim        SurahName   = "Surat At-Tahrim"
	SuraNameMulk          SurahName   = "Surat Al-Mulk"
	SuraNameQalam         SurahName   = "Surat Al-Qalam"
	SuraNameHaqqah        SurahName   = "Surat Al-Haqqah"
	SuraNameMaarij        SurahName   = "Surat Al-Ma'arij"
	SuraNameNuh           SurahName   = "Surat Nuh"
	SuraNameJinn          SurahName   = "Surat Al-Jinn"
	SuraNameMuzzammil     SurahName   = "Surat Al-Muzzammil"
	SuraNameMuddathir     SurahName   = "Surat Al-Muddathir"
	SuraNameQiyamah       SurahName   = "Surat Al-Qiyāmah"
	SuraNameInsan         SurahName   = "Surat Al-Insan"
	SuraNameMursalat      SurahName   = "Surat Al-Mursalat"
	SuraNameNaba          SurahName   = "Surat An-Naba"
	SuraNameNaziat        SurahName   = "Surat An-Nazi'at"
	SuraNameAbasa         SurahName   = "Surat 'Abasa"
	SuraNameTakwir        SurahName   = "Surat At-Takwir"
	SuraNameInfitar       SurahName   = "Surat Al-Infitar"
	SuraNameMutaffifin    SurahName   = "Surat Al-Mutaffifin"
	SuraNameInshiqaq      SurahName   = "Surat Al-Inshiqaq"
	SuraNameBuruj         SurahName   = "Surat Al-Buruj"
	SuraNameTariq         SurahName   = "Surat At-Tariq"
	SuraNameAlaa          SurahName   = "Surat Al-A'laa"
	SuraNameGhashiyah     SurahName   = "Surat Al-Ghashiyah"
	SuraNameFajr          SurahName   = "Surat Al-Fajr"
	SuraNameBalad         SurahName   = "Surat Al-Balad"
	SuraNameShams         SurahName   = "Surat Ash-Shams"
	SuraNameLail          SurahName   = "Surat Al-Lail"
	SuraNameDuha          SurahName   = "Surat Ad-Duha"
	SuraNameSharh         SurahName   = "Surat Ash-Sharh"
	SuraNameTin           SurahName   = "Surat At-Tin"
	SuraNameAlaq          SurahName   = "Surat Al-'Alaq"
	SuraNameQadr          SurahName   = "Surat Al-Qadr"
	SuraNameBayyinah      SurahName   = "Surat Al-Bayyinah"
	SuraNameZalzalah      SurahName   = "Surat Az-Zalzalah"
	SuraNameAdiyat        SurahName   = "Surat Al-'Adiyat"
	SuraNameQariah        SurahName   = "Surat Al-Qari'ah"
	SuraNameTakathur      SurahName   = "Surat At-Takathur"
	SuraNameAsr           SurahName   = "Surat Al-'Asr"
	SuraNameHumazah       SurahName   = "Surat Al-Humazah"
	SuraNameFil           SurahName   = "Surat Al-Fil"
	SuraNameQuraish       SurahName   = "Surat Quraish"
	SuraNameMaun          SurahName   = "Surat Al-Ma'un"
	SuraNameKawthar       SurahName   = "Surat Al-Kawthar"
	SuraNameKafirun       SurahName   = "Surat Al-Kafirun"
	SuraNameNasr          SurahName   = "Surat An-Nasr"
	SuraNameLahab         SurahName   = "Surat Al-Masad"
	SuraNameIkhlas        SurahName   = "Surat Al-Ikhlas"
	SuraNameFalaq         SurahName   = "Surat Al-Falaq"
	SuraNameNas           SurahName   = "Surat An-Nas"
)

type SurahNumber int
type SurahName string

// Needs to be initialized
var SurahNumToName = map[int]string{}
