package models

// Needs to be initialized
var SurahNumToName = map[int]string{}

const (
	SurahNumberFatiha     int = 1
	SurahNumberBaqarah    int = 2
	SurahNumberAlImran    int = 3
	SurahNumberNisa       int = 4
	SurahNumberMaidah     int = 5
	SurahNumberAnam       int = 6
	SurahNumberAraf       int = 7
	SurahNumberAnfal      int = 8
	SurahNumberTawbah     int = 9
	SurahNumberYunus      int = 10
	SurahNumberHud        int = 11
	SurahNumberYusuf      int = 12
	SurahNumberRad        int = 13
	SurahNumberIbrahim    int = 14
	SurahNumberHijr       int = 15
	SurahNumberNahl       int = 16
	SurahNumberIsra       int = 17
	SurahNumberKahf       int = 18
	SurahNumberMaryam     int = 19
	SurahNumberTaha       int = 20
	SurahNumberAnbiya     int = 21
	SurahNumberHajj       int = 22
	SurahNumberMuminun    int = 23
	SurahNumberNur        int = 24
	SurahNumberFurqan     int = 25
	SurahNumberShuara     int = 26
	SurahNumberNaml       int = 27
	SurahNumberQasas      int = 28
	SurahNumberAnkabut    int = 29
	SurahNumberRum        int = 30
	SurahNumberLuqman     int = 31
	SurahNumberSajdah     int = 32
	SurahNumberAhzab      int = 33
	SurahNumberSaba       int = 34
	SurahNumberFatir      int = 35
	SurahNumberYasin      int = 36
	SurahNumberSaffat     int = 37
	SurahNumberSad        int = 38
	SurahNumberZumar      int = 39
	SurahNumberGhafir     int = 40
	SurahNumberFussilat   int = 41
	SurahNumberShura      int = 42
	SurahNumberZukhruf    int = 43
	SurahNumberDukhan     int = 44
	SurahNumberJathiyah   int = 45
	SurahNumberAhqaf      int = 46
	SurahNumberMuhammad   int = 47
	SurahNumberFath       int = 48
	SurahNumberHujurat    int = 49
	SurahNumberQaf        int = 50
	SurahNumberDhariyat   int = 51
	SurahNumberTur        int = 52
	SurahNumberNajm       int = 53
	SurahNumberQamar      int = 54
	SurahNumberRahman     int = 55
	SurahNumberWaqiah     int = 56
	SurahNumberHadid      int = 57
	SurahNumberMujadilah  int = 58
	SurahNumberHashr      int = 59
	SurahNumberMumtahanah int = 60
	SurahNumberSaff       int = 61
	SurahNumberJumuah     int = 62
	SurahNumberMunafiqun  int = 63
	SurahNumberTaghabun   int = 64
	SurahNumberTalaq      int = 65
	SurahNumberTahrim     int = 66
	SurahNumberMulk       int = 67
	SurahNumberQalam      int = 68
	SurahNumberHaqqah     int = 69
	SurahNumberMaarij     int = 70
	SurahNumberNuh        int = 71
	SurahNumberJinn       int = 72
	SurahNumberMuzzammil  int = 73
	SurahNumberMuddathir  int = 74
	SurahNumberQiyamah    int = 75
	SurahNumberInsan      int = 76
	SurahNumberMursalat   int = 77
	SurahNumberNaba       int = 78
	SurahNumberNaziat     int = 79
	SurahNumberAbasa      int = 80
	SurahNumberTakwir     int = 81
	SurahNumberInfitar    int = 82
	SurahNumberMutaffifin int = 83
	SurahNumberInshiqaq   int = 84
	SurahNumberBuruj      int = 85
	SurahNumberTariq      int = 86
	SurahNumberAla        int = 87
	SurahNumberGhashiyah  int = 88
	SurahNumberFajr       int = 89
	SurahNumberBalad      int = 90
	SurahNumberShams      int = 91
	SurahNumberLail       int = 92
	SurahNumberDuha       int = 93
	SurahNumberSharh      int = 94
	SurahNumberTin        int = 95
	SurahNumberAlaq       int = 96
	SurahNumberQadr       int = 97
	SurahNumberBayyinah   int = 98
	SurahNumberZalzalah   int = 99
	SurahNumberAdiyat     int = 100
	SurahNumberQariah     int = 101
	SurahNumberTakathur   int = 102
	SurahNumberAsr        int = 103
	SurahNumberHumazah    int = 104
	SurahNumberFil        int = 105
	SurahNumberQuraish    int = 106
	SurahNumberMaun       int = 107
	SurahNumberKauthar    int = 108
	SurahNumberKafirun    int = 109
	SurahNumberNasr       int = 110
	SurahNumberLahab      int = 111
	SurahNumberIkhlas     int = 112
	SurahNumberFalaq      int = 113
	SurahNumberNas        int = 114
)

const (
	SuraNameFatiha     string = "Surat Al-Fatiha"
	SuraNameBaqarah    string = "Surat Al-Baqarah"
	SuraNameAlImran    string = "Surat Al-Imran"
	SuraNameNisa       string = "Surat Al-Nesaa"
	SuraNameMaidah     string = "Surat Al-Ma'idah"
	SuraNameAnam       string = "Surat Al-An'aam"
	SuraNameAraf       string = "Surat Al-A'raf"
	SuraNameAnfal      string = "Surat Al-Anfal"
	SuraNameTawbah     string = "Surat At-Tawbah"
	SuraNameYunus      string = "Surat Yunus"
	SuraNameHud        string = "Surat Hud"
	SuraNameYusuf      string = "Surat Yusuf"
	SuraNameRad        string = "Surat Ar-Ra'd"
	SuraNameIbrahim    string = "Surat Ibrahim"
	SuraNameHijr       string = "Surat Al-Hijr"
	SuraNameNahl       string = "Surat An-Nahl"
	SuraNameIsra       string = "Surat Al-Isra'"
	SuraNameKahf       string = "Surat Al-Kahf"
	SuraNameMaryam     string = "Surat Maryam"
	SuraNameTaha       string = "Surat Taha"
	SuraNameAnbiya     string = "Surat Al-Anbiya"
	SuraNameHajj       string = "Surat Al-Hajj"
	SuraNameMuminun    string = "Surat Al-Mu'minun"
	SuraNameNur        string = "Surat An-Nur"
	SuraNameFurqan     string = "Surat Al-Furqan"
	SuraNameShuara     string = "Surat Ash-Shu'ara"
	SuraNameNaml       string = "Surat An-Naml"
	SuraNameQasas      string = "Surat Al-Qasas"
	SuraNameAnkabut    string = "Surat Al-Ankabut"
	SuraNameRum        string = "Surat Ar-Rum"
	SuraNameLuqman     string = "Surat Luqman"
	SuraNameSajdah     string = "Surat As-Sajdah"
	SuraNameAhzab      string = "Surat Al-Ahzab"
	SuraNameSaba       string = "Surat Saba"
	SuraNameFatir      string = "Surat Fatir"
	SuraNameYasin      string = "Surat Ya-Sin"
	SuraNameSaffat     string = "Surat As-Saffat"
	SuraNameSad        string = "Surat Sad"
	SuraNameZumar      string = "Surat Az-Zumar"
	SuraNameGhafir     string = "Surat Ghafir"
	SuraNameFussilat   string = "Surat Fussilat"
	SuraNameShura      string = "Surat Ash-Shura"
	SuraNameZukhruf    string = "Surat Az-Zukhruf"
	SuraNameDukhan     string = "Surat Ad-Dukhan"
	SuraNameJathiyah   string = "Surat Al-Jathiyah"
	SuraNameAhqaf      string = "Surat Al-Ahqaf"
	SuraNameMuhammad   string = "Surat Muhammad"
	SuraNameFath       string = "Surat Al-Fath"
	SuraNameHujurat    string = "Surat Al-Hujurat"
	SuraNameQaf        string = "Surat Qaf"
	SuraNameDhariyat   string = "Surat Ath-Thariyat"
	SuraNameTur        string = "Surat At-Tur"
	SuraNameNajm       string = "Surat An-Najm"
	SuraNameQamar      string = "Surat Al-Qamar"
	SuraNameRahman     string = "Surat Ar-Rahman"
	SuraNameWaqiah     string = "Surat Al-Waqi'ah"
	SuraNameHadid      string = "Surat Al-Hadid"
	SuraNameMujadilah  string = "Surat Al-Mujadila"
	SuraNameHashr      string = "Surat Al-Hashr"
	SuraNameMumtahanah string = "Surat Al-Mumtahinah"
	SuraNameSaff       string = "Surat As-Saff"
	SuraNameJumuah     string = "Surat Al-Jumu'ah"
	SuraNameMunafiqun  string = "Surat Al-Munafiqun"
	SuraNameTaghabun   string = "Surat At-Taghabun"
	SuraNameTalaq      string = "Surat At-Talaq"
	SuraNameTahrim     string = "Surat At-Tahrim"
	SuraNameMulk       string = "Surat Al-Mulk"
	SuraNameQalam      string = "Surat Al-Qalam"
	SuraNameHaqqah     string = "Surat Al-Haqqah"
	SuraNameMaarij     string = "Surat Al-Ma'arij"
	SuraNameNuh        string = "Surat Nuh"
	SuraNameJinn       string = "Surat Al-Jinn"
	SuraNameMuzzammil  string = "Surat Al-Muzzammil"
	SuraNameMuddathir  string = "Surat Al-Muddathir"
	SuraNameQiyamah    string = "Surat Al-Qiyāmah"
	SuraNameInsan      string = "Surat Al-Insan"
	SuraNameMursalat   string = "Surat Al-Mursalat"
	SuraNameNaba       string = "Surat An-Naba"
	SuraNameNaziat     string = "Surat An-Nazi'at"
	SuraNameAbasa      string = "Surat 'Abasa"
	SuraNameTakwir     string = "Surat At-Takwir"
	SuraNameInfitar    string = "Surat Al-Infitar"
	SuraNameMutaffifin string = "Surat Al-Mutaffifin"
	SuraNameInshiqaq   string = "Surat Al-Inshiqaq"
	SuraNameBuruj      string = "Surat Al-Buruj"
	SuraNameTariq      string = "Surat At-Tariq"
	SuraNameAlaa       string = "Surat Al-A'laa"
	SuraNameGhashiyah  string = "Surat Al-Ghashiyah"
	SuraNameFajr       string = "Surat Al-Fajr"
	SuraNameBalad      string = "Surat Al-Balad"
	SuraNameShams      string = "Surat Ash-Shams"
	SuraNameLail       string = "Surat Al-Lail"
	SuraNameDuha       string = "Surat Ad-Duha"
	SuraNameSharh      string = "Surat Ash-Sharh"
	SuraNameTin        string = "Surat At-Tin"
	SuraNameAlaq       string = "Surat Al-'Alaq"
	SuraNameQadr       string = "Surat Al-Qadr"
	SuraNameBayyinah   string = "Surat Al-Bayyinah"
	SuraNameZalzalah   string = "Surat Az-Zalzalah"
	SuraNameAdiyat     string = "Surat Al-'Adiyat"
	SuraNameQariah     string = "Surat Al-Qari'ah"
	SuraNameTakathur   string = "Surat At-Takathur"
	SuraNameAsr        string = "Surat Al-'Asr"
	SuraNameHumazah    string = "Surat Al-Humazah"
	SuraNameFil        string = "Surat Al-Fil"
	SuraNameQuraish    string = "Surat Quraish"
	SuraNameMaun       string = "Surat Al-Ma'un"
	SuraNameKawthar    string = "Surat Al-Kawthar"
	SuraNameKafirun    string = "Surat Al-Kafirun"
	SuraNameNasr       string = "Surat An-Nasr"
	SuraNameLahab      string = "Surat Al-Masad"
	SuraNameIkhlas     string = "Surat Al-Ikhlas"
	SuraNameFalaq      string = "Surat Al-Falaq"
	SuraNameNas        string = "Surat An-Nas"
)
